'use client'

import { Inter } from "next/font/google";
import "@/src/css/style.css";
import { ApolloProvider } from "@apollo/client";
import client from "@/apollo/client/client";
// import Header from "@/src/components/Header";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "e-com",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          {/* <Header /> */}
          {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
